name: Google Sheets Data Refresh

on:
  schedule:
    - cron: "47 7 * * *"   # 1:05 PM IST
  workflow_dispatch:

jobs:
  refresh-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Refresh Google Sheet
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          for i in 1 2 3; do
            python ./refresh_google_sheet.py && break
            echo "Attempt $i failed. Retrying..."
            sleep 5
          done

      - name: Send Success Email
        if: success()
        env:
          STATUS: SUCCESS
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python ./send_email.py

      - name: Send Failure Email
        if: failure()
        env:
          STATUS: FAILURE
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python ./send_email.py

